version: '3.7'

services:
    frontend:
      container_name: sellerbot_frontend
      image: losimonassi/sellerbot_frontend
      stdin_open: true
      tty: true
      ports:
        - '8080:8080'
      environment: 
        - CHOKIDAR_USEPOLLING=true
        - HOST=0.0.0.0