version: '3.7'

services:
    frontend:
      container_name: sellerbot_frontend
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - './src:/app/src'
        - '/app/node_modules'
      stdin_open: true
      tty: true
      ports:
        - '8080:8080'
      environment: 
        - CHOKIDAR_USEPOLLING=true