version: "3.8"
services:
  frontend:
      build:
          dockerfile: Dockerfile
      image: football-coach-frontend:latest
      ports:
          - "8080:8080"
      volumes:
          - ./frontend:/my-app