version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage # para desenvolvimento
    ports:
      - '8080:8080'
    environment: 
      - NODE_ENV=development
    volumes:
      - '/app/node_modules'
      - './:/app'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage # para produção
    ports:
      - '80:80'
    environment: 
      - NODE_ENV=production
