#dockercompose
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development-stage}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment: 
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - '/app/node_modules'
      - './:/app'

